### ISSUE TITLE
ddclient runs as root by default.

### ISSUE THREAD

**Issue by tts3c** [ddclient/ddclient#109]
The ddclient service runs as root by default. The default cron config also suggest to run the client as root. 
$ ps -aux | grep ddclient
root      655098  0.0  0.0  21100 14296 ?        S    10:43   0:00 ddclient - sleeping for 300 seconds

The client can also run as a user, provided the files permissions are set accordingly. It should not run as root by default, specially if it is running as a daemon.

**Comment by wimpunk** [comment]
Actually, it depends on the distrubution you're using or the configuration you made.  So if you installed ddclient using the package of your distribution you should better ask to maintainer of the package to change the rights.

**Comment by rhansen** [comment]
I think this is in-scope for the ddclient project, so I'm removing the wontfix label.

In general, daemons should write the PID file as root then drop privileges. (The PID file should be owned by root so that an attacker that compromises ddclient can't cause the init system to kill another process by writing the other process's PID in the ddclient PID file. systemd has some safety checks to avoid this, but it's still good practice.) With ddclient as it is now, the only way to write a PID file as root and then drop privileges is to launch ddclient via a helper utility that daemonizes, writes the PID file, drops privileges, then execs ddclient with `-foreground`. If distributions are expected to do this then ddclient's daemonization functionality might as well be removed.

**Comment by taimoortalpur** [comment]
For more info. I am using arch linux and have also reported it to the distribution. 
https://bugs.archlinux.org/task/66893?string=ddclient

**Comment by wimpunk** [comment]
@rhansen We can suggest users to use another user but we will have to think about how to fix the cache location.  I really don't believe this is something which has to fixed in the code, although we could check which user is running ddclient and switch to another cache location but I don't think there are any recommentations about cache locations for non-root users.

**Comment by rhansen** [comment]
I don't think we need to do anything. As long as the cache file isn't opened until after privileges are dropped, users can simply chown `/var/cache/ddclient` to the unprivileged user and everything should just work. (As far as I can tell, nothing in [Debian policy](https://www.debian.org/doc/debian-policy/) prohibits changing the owner of `/var/cache/<package>` to an unprivileged user.)

**Comment by wimpunk** [comment]
I was thinking about a multiuser system where user A runs ddclient and user B runs ddclient but if you think about running it as a demon, it would make sense by just changing the ownership of the cache file.  Maybe we could add some info about the readme on how to do it, although that's pretty obvious for most of the users.

**Comment by SuperSandro2000** [comment]
This seems to be a very niche case to worry about to be honest. You could just use the multi domain setup for most cases.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
