### ISSUE TITLE
Adopt Debian's "usev6" option

### ISSUE THREAD

**Issue by rhansen** [ddclient/ddclient#151]
Debian [patches](https://salsa.debian.org/debian/ddclient/-/blob/67a138aa3d98d70f01766123f58ef40e98693fd4/debian/patches/usev6.diff) ddclient to add a new `usev6` option. We should investigate applying that patch here.

**Comment by SuperSandro2000** [comment]
There is also a more comprehensive PR https://github.com/ddclient/ddclient/pull/40

**Comment by dkerr64** [comment]
Its been a long time since I submitted #40 and frankly I had given up on anyone paying any attention to it -- and in frustration with the apparent abandonment of ddclient we (@abelbeck and I) copied ddclient over to https://github.com/astlinux-project/ddclient-curl which I would encourage you to look at.  Unfortunately it is not mergeable into here, but we did get IPv6 into a very good place and we got rid of all the perl networking (replaced by curl).  I don't know if anything has changed, but at the time it was absolutely necessary to use curl for IPv6, could not use perl.
Please let me know if you are serious about getting IPv6 to work well and I will look to assist.  But as I said, I gave up on pushing several years ago.

**Comment by SuperSandro2000** [comment]
I think the current main goal is to merge the Debian patch to get the ipv6 over the IP command. We probably need other ways down the line. I am not so deep into perl to know if it's networking has better ipv6 support by now.

At least from my part I would be interested in getting it working but I can only contribute code review, design questions, merges and the occasional bug fix.

I think the best plan would be that we first get that patch into here and then research if we can do ipv6 in pure perl or need curl or a new module. If @rhansen is down for it and has the time for it maybe you two can collaborate on that?

**Comment by abelbeck** [comment]
Adding general IPv6 support is more complicated than just the referenced Debian patch above.

**Comment by dkerr64** [comment]
I agree with @abelbeck .  IPv6 is very different from IPv4.  I am encouraged to see that ddclient has a lot of activity over the last month or two -- it is long overdue as it had languished without any attention for years -- and I would like to see it brought up-to-date with support for IPv6.  But please don't do it piecemeal.   In particular I strongly encourage not attempting to do IPv6 "networking" inside the app, as noted in the comments for #40 it is much better to "outsource" that to curl.

**Comment by rhansen** [comment]
I guess I should have looked through the existing PRs and issues before opening this issue. :smile: I had my Debian maintainer hat on and was only concerned about reducing the number of patches in the Debian package.

I'll take a look at #40.

**Comment by dkerr64** [comment]
@rhansen please hold off for now... I looked at #40 and there are too many merge conflicts after 4 years of changes.  I am getting my fork up-to-date with your master and will apply the IPv6 updates to that.  When I have a clean merge I will submit a new pull request.  You can follow along here if you want... https://github.com/dkerr64/ddclient/tree/IPv6
Thanks

**Comment by rhansen** [comment]
Closing this in favor of a more comprehensive solution.
