### ISSUE TITLE
Questions: meaning of time-options

### ISSUE THREAD

**Issue by RichardBeisser** [ddclient/ddclient#282]
Hello,

because some options are not described in the help (and also not in manpage), what exactly make these options:
min-error-interval
min-interval
max-interval
mtime
warned-min-error-interval
warned-min-interval

What means when the value is 0?

Thanks

**Comment by dkerr64** [comment]
You should not need to set any of these, they control how often ddclient attempts to update the IP address at a service and are intended to avoid flooding the server with requests (which might get you locked out). 

`min-interval` defaults to 30 seconds... ddclient will prevent you from updating the IP more frequently than once every 30 seconds... unless an error was returned by the server in which case it will not update for `min-error-interval` (defaults to 5 minutes).   And `max-interval` (default 25 days) means update your IP at the server at least once every 25 days even if the IP address has not changed.  The other variables are used to record actual times events occur so that ddclient can calculate if the interval(s) have expired or not.
