### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by trogper** [ddclient/ddclient#365]
I run ddclient on raspberry pi. Today I noticed high memory usage, ddclient has claimed 103MB according to htop.
My environment:
perl 5.28.1
ddclient 3.8.3 (package version 3.8.3-1.1)
Easpbian 10
Current uptime is 91 days.

`/etc/ddclient.conf`
```
protocol=dyndns2
 use=web, web=checkip.dynu.com
server=api.dynu.com
ssl=yes
login=trogper
password='<<<redacted>>>'
trogper.cf,raspberrypi.ga


protocol=dyndns2
 use=web, web=https://ddns.webbox.sk/checkip
server=ddns.webbox.sk
ssl=yes
login=trogper
password='<<<redacted>>>'
*.raspberrypi.ga,@raspberrypi.ga
```

what else should I provide?

**Comment by daradib** [comment]
ddclient also configured with dyndns2, web, ssl=yes on EdgeRouter X was using 80MB resident, out of 256 MB system memory. Load average was 14(!) and DNS, SSH, even local systemctl commands were timing out, which immediately resolved after killing ddclient.

 - Perl 5.24.1
 - ddclient 3.8.3 (package version 3.8.3-1.1)
 - EdgeOS v2.0.9-hotfix.2 (latest release), based on Vyatta and Debian 9
 - Linux 4.14.54-UBNT
 - uptime 144 days

```
$ ps aux --sort -rss
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      3590  0.2 32.0  89852 81076 ?        D     2021 617:41 ddclient - connecting to [...]
```

Did not find any helpful warnings in syslog. I also tried looking in the ddclient changelog to see if this has been fixed in a newer version.

**Comment by DaveSophoServices** [comment]
What was it using after a restart? What's the baseline for that perl 
version?

**Comment by trogper** [comment]
Raspberry Pi 2
Raspbian 10
Perl 5.28.1
ddclient 3.8.3-1.1

```
$ uptime
 22:14:22 up 56 days,  2:12,  3 users,  load average: 0.08, 0.10, 0.06
$ ps aux --sort -rss
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ddclient   297  0.0  6.3  71312 63016 ?        Ss    2021  29:17 ddclient - sleeping for 240 seconds
$ sudo service ddclient restart
$ ps aux --sort -rss
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ddclient 29810  2.3  1.4  18804 14100 ?        Ss   22:16   0:01 ddclient - sleeping for 260 seconds
```
