### ISSUE TITLE
https by default?

### ISSUE THREAD

**Issue by jerabaul29** [ddclient/ddclient#383]
According to deSec manual, "As of the time of this writing, ddclient does not use an encrypted HTTPS connection by default.", see https://desec.readthedocs.io/en/latest/dyndns/configure.html .

- is it still true?
- if yes, any reason why it is so?
- any possibility to switch to https by default?

**Comment by SuperSandro2000** [comment]
I have updated all defaults to https which support that. The sites that use a generic method I probably missed. Please still set ``ssl=1`` if your service supports that but it should now be less likely to end up with http.

> if yes, any reason why it is so?

Because some services for some reason beyond me still do not support https. Maybe they are going to be dropped in the future and https will become the default.

> any possibility to switch to https by default?

Maybe something todo 4.1 but since I can't test every service I don't think that will happen soon.
