### ISSUE TITLE
macOS: ddclient --HEAD broken on Homebrew

### ISSUE THREAD

**Issue by ylluminate** [ddclient/ddclient#439]
Thought you might want to be aware:
https://github.com/Homebrew/homebrew-core/issues/106810

With the potentiality of `--HEAD` going away in homebrew, it might be worth considering pushing a full new version vs any more RCs/pre-release sooner than later.

It would also facilitate MacPorts probably updating since many of us much prefer MacPorts to Homebrew.

**Comment by SuperSandro2000** [comment]
Oh, I didn't even know we had brew or any darwin support. 😂 

I am not planning to invest any time myself into anything darwin related, so if something is broken it needs to be fixed by the community. I am probably pushing the new release soonish since I am not getting much feedback about the rc ones.

**Comment by ylluminate** [comment]
Thanks. Yeah, you've got a pretty useful tool here that's become the goto in this arena. I've found it to be essential with isolated macOS virtual machines since Apple Silicon devices are not always easy to get your hands on and we have to share such virtual machines with other team members to test software.
