### ISSUE TITLE
Update of IPV6 in dynu.com

### ISSUE THREAD

**Issue by rolblo12** [ddclient/ddclient#475]
I am using ddclient 3.9.1 on Ubuntu 22.04. 
My dynamic DNS provider is dynu.com. They describe their update protocol in https://www.dynu.com/DynamicDNS/IP-Update-Protocol.
I would like to update both the IPv4 address (via use=web, web=**https://api64.ipify.org/**) and the IPv6 address (via **usev6**=if, if=<interface>). Dynu.com suggest using ddclient with the dndns2 protocol.
Just updating the IPv4 works correctly, however, the update https request for the IPv6 address contains the key word  "myip" instead "myipv6", as dynu.com describes in their API.
Is there some workaround?

**Comment by SuperSandro2000** [comment]
> Is there some workaround?

Probably not, this would require a code change.

**Comment by tduboys** [comment]
Hi,
I tried to update dyndns2 protocol to use the ipv4/ipv6 logic
https://github.com/ddclient/ddclient/pull/502
But as I read on the link you give, it does not work with the same syntax

I followod the dyn.com syntax (that looks the reference for dyndns2, for wikipedia…) and it uses only one param `myip` that can contain ipv4, ipv6 or both separated by comma https://help.dyn.com/remote-access-api/perform-update/
But dynu.com seems to need a `myip` and `myipv6` params. so the code will probably not work.

if the only myip param dont work, it will require a new provider because there is no provider that uses `myipv6` param on url
