### ISSUE TITLE
ddclient can't determine IP for vlan interface

### ISSUE THREAD

**Issue by admin-eschaeffer58** [ddclient/ddclient#540]
I have an opnsense install running the latest version (23.1.7_3-amd64) and was working to install Dynamic DNS. I got both cloudflare and google setup but when the service goes to read the interface's IP address, it logs this entry:

> 2023-05-21T20:31:58-05:00	Notice	ddclient[419]	39522 - [meta sequenceId="2"] FAILED: Unable to obtain information for 'em0_vlan' -- missing ip or ifconfig command

The actual interface name is em0_vlan10. This router is nested in the network and doesn't have a direct assigned public IP. I have it set up in a lab where I'm trying to get this all configured before deploying it to the remote site it's going to live. 

Here are the contents of `/usr/local/etc/ddclient.conf`

```
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
verbose=yes

ssl=yes

usev4=ifv4, if=em0_vlan10, \
protocol=googledomains, \
login=<snip>, \
password=<snip> \
unmc.heartlandready.com

usev4=ifv4, if=em0_vlan10, \
protocol=cloudflare, \
zone=heartlandready.com, \
password=<snip> \
unmc.heartlandready.com
 ```

It looks like the config is setup correctly but somewhere down the line, the number is being dropped. I found the source and simulated the input and figured out that the address seems to be processed properly but there's a conditional that looks to be the issue.

Debug Notebook: https://cocalc.com/share/public_paths/9f8375ebc4525456211ffde578180b7a51e0d400

Based on that the is_global method is returning false (because it's an internal IP address) and not returning anything. Is it possible to have that condition respect the setting in the interface (block private networks)?

However, commenting that out didn't solve the issue. The error message appears to be coming from here:
https://github.com/ddclient/ddclient/blob/841ffcbdaa009687e5fb390c4527055e929f959a/ddclient.in#L3207

**Comment by SuperSandro2000** [comment]
> Is it possible to have that condition respect the setting in the interface (block private networks)?

I don't know but you can create a PR.

**Comment by rhyser9** [comment]
The error doesn't seem to stem from `is_global`, but rather, the interface name is being truncated.

`Unable to obtain information for 'em0_vlan'` instead of `'emo_vlan10'`

On my end, I'm seeing the following sequence of debug messages:
```
# /usr/local/etc/ddclient.conf

usev4=ifv4, if=vtnet0_vlan1, \
protocol=namecheap, \
login=<snip>, \
password=<snip> \
<snip>.com
```
```
WARNING: 'if-skip' is deprecated and does nothing for IPv4
FAILED: Unable to obtain information for 'vtnet0_v' -- missing ip or ifconfig command
WARNING: <snip>.com: unable to determine IPv4 address with strategy usev4=ifv4
```

**Comment by rhyser9** [comment]
Traced this further. The cause is due to a slight misconfiguration in the `.conf` file. `usev4=ifv4, if=em0_vlan10` should be `usev4=ifv4, ifv4=em0_vlan10`.

https://github.com/ddclient/ddclient/blob/841ffcbdaa009687e5fb390c4527055e929f959a/ddclient.in#L3327-L3349

The `get_ipv4` command uses the contents of the `usev4` field to retrieve the interface to check. Because it can't find any configuration under `ifv4=`, it falls back to `ifv4=default`.

```
config{<snip>.com}{usev4} : ifv4
config{<snip>.com}{if} : vtnet0_vlan500
config{<snip>.com}{ifv4} : default
config{<snip>.com}{ifv6} : default
```

This causes `get_ip_from_interface` to call `get_default_interface` to try and figure out the 'best' interface to check, by checking default routes. `get_default_interface` tries to call `ip -4 -o route list match default` to figure this out, but opnsense doesn't have the iproute2 package by default, so it falls back to `netstat -rn -4`, which gives the following output:
```
DEBUG:    default            <ISP>              UGS    vtnet0_v
```

A couple of ways to resolve this:
1) An upstream fix in os-ddclient to generate the correct config with `ifv4=` instead of `if=`
2) 




```
WARNING:  'if-skip' is deprecated and does nothing for IPv4
DEBUG:    Reply from 'netstat -rn -4' :
DEBUG:    ------
DEBUG:    Routing tables
DEBUG:
DEBUG:    Internet:
DEBUG:    Destination        Gateway            Flags     Netif Expire
DEBUG:    default            <ISP>              UGS    vtnet0_v
DEBUG:    <ISP>/24           link#8             U      vtnet0_v
DEBUG:    <ISP>              link#8             UHS         lo0
DEBUG:    127.0.0.1          link#3             UH          lo0
DEBUG:    192.168.0.0/24     link#6             U      vtnet0_v
DEBUG:    192.168.0.2        link#6             UHS         lo0
DEBUG:    192.168.2.0/24     link#7             U      vtnet0_v
DEBUG:    192.168.2.1        link#7             UHS         lo0
DEBUG:    ------
DEBUG:    Default routes found for IPv4 :
DEBUG:    default            <ISP>              UGS    vtnet0_v
FAILED:   Unable to obtain information for 'vtnet0_v' -- missing ip or ifconfig command
DEBUG:    Reply from 'missing ip or ifconfig command' :
DEBUG:    ------
DEBUG:    ------
DEBUG:    get_ipv4: using (ifv4, default) reports <undefined>
WARNING:  <snip>.com: unable to determine IPv4 address with strategy usev4=ifv4
DEBUG:
DEBUG:    nic_namecheap1_update -------------------
Use of uninitialized value $_[0] in sprintf at /usr/local/sbin/ddclient line 2179.
INFO:     setting IP address to  for <snip>.com
UPDATE:   updating <snip>.com
```

**Comment by rhyser9** [comment]
Traced this further. The cause is due to a slight misconfiguration in the `.conf` file. `usev4=ifv4, if=em0_vlan10` should be `usev4=ifv4, ifv4=em0_vlan10`.

https://github.com/ddclient/ddclient/blob/841ffcbdaa009687e5fb390c4527055e929f959a/ddclient.in#L3327-L3349

The `get_ipv4` command uses the contents of the `usev4` field to retrieve the interface to check. Because it can't find any configuration under `ifv4=`, it falls back to `ifv4=default`.

```
config{<snip>.com}{usev4} : ifv4
config{<snip>.com}{if} : vtnet0_vlan500
config{<snip>.com}{ifv4} : default
config{<snip>.com}{ifv6} : default
```

https://github.com/ddclient/ddclient/blob/841ffcbdaa009687e5fb390c4527055e929f959a/ddclient.in#L3176-L3178
This causes `get_ip_from_interface` to call `get_default_interface` to try and figure out the 'best' interface to check, by checking default routes. `get_default_interface` tries to call `ip -4 -o route list match default` to figure this out, but FreeBSD doesn't have the iproute2 package, so it falls back to `netstat -rn -4`, which gives the following output, with the truncated interface name:
```
DEBUG:    default            <ISP>              UGS    vtnet0_v
```

A couple of ways to resolve this:
1) An upstream fix in os-ddclient to generate the correct config with `ifv4=` instead of `if=`, so that ddclient never hits `get_default_interface`.
2) Update [L3178](https://github.com/ddclient/ddclient/blob/841ffcbdaa009687e5fb390c4527055e929f959a/ddclient.in#L3178) from `netstat -rn -$ipver` to `netstat -Wrn -$ipver` to prevent truncating fields when ddclient runs `get_default_interface`. Might necessitate adjusting the subsequent parser to extract the interface name from the netstat output, haven't looked at that yet.

**Comment by admin-eschaeffer58** [comment]
> The error doesn't seem to stem from is_global; rather, the interface name is being truncated.
Agreed. It was a layered issue. The is_global script would prevent the private IP from being pushed to the DNS record, but it never gets that far due to the truncation issue you pointed out. :)

Wow! Thank you for all of the work here! I will work with opensense to create a pull request to fix the config generation :)
