### ISSUE TITLE
Invalid protocol for OVH

### ISSUE THREAD

**Issue by guillemc23** [ddclient/ddclient#571]
I'm having trouble setting ddclient for OVH. I'm getting the following warning:

`raspberrypi ddclient[1233]: WARNING:  file /etc/ddclient.conf, line 16: Invalid Value for keyword 'protocol' = 'ovh'`

Not sure what's wrong, shouldn't `ovh` be a valid protocol? It's on the config file in this repo:

https://github.com/ddclient/ddclient/blob/ef496d108fea294ef83d7be6a6f9eb40ae3fc25c/ddclient.conf.in#L280-L286

**Comment by jortkoopmans** [comment]
Not sure what might be the issue, the example config you've posted seems right (not a ovh user myself).
However, OVH has been recently added (specifically in pre-releases from v3.10.0_1 onwards, but only official release v3.10.0 has it), could you verify the version of ddclient you're running?

Note that also some ovh bugs were fixed in the current prerelease v3.11.0_1. You may have best of luck building from source.

**Comment by guillemc23** [comment]
Hey @jortkoopmans, I am using 3.8.3-1.1 which is the version that was installed automatically in my Raspberry Pi.

I was trying to update three subdomains at the same time which was returning errors also when using a most standard `protocol=dyndns2`. I ended up setting up three different usernames to update one subdomain each, which did the trick for me. 

When I update the package's version, I'll try again setting up ovh as the protocol and reopen the issue if it persists! Thank you!
