### ISSUE TITLE
Easydns still not working

### ISSUE THREAD

**Issue by lemppari** [ddclient/ddclient#582]
I opened issue #354 couple of years ago and it was closed as not planned. Since ddclient seems to be under work again, maybe this could be revisited. The actual update is working but the return codes are now html and not parsed ok by ddclient. Here is a sample from the lastest version 3.11.1.

```
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  Content-Type: text/html; charset=UTF-8
RECEIVE:
RECEIVE:  <HTML><BODY><FONT FACE="sans-serif" SIZE="-1">OK<br />
RECEIVE:  <hr noshade size="1">
RECEIVE:  no update required for xxx.yyy to x.y.z.zz<br />
RECEIVE:  </FONT></BODY></HTML>
FAILED:   updating xxx.yyy: unexpected status (<HTML><BODY><FONT FACE="sans-serif" SIZE="-1">OK<br />)
```

**Comment by Glandvador** [comment]
I modified the code as below. This is crude, but it works for me with one domain.
The change removes all the HTML tags <...> from the response (only in 'results2' state). 
It also seems that result codes changed: OK instead NOERROR and TOO_FREQ instead of TOOSOON. All other changes, should be caught by the 'unexpected status' line. In my opinion these changes should work even with previous responses.

`--- /usr/sbin/ddclient	2023-11-29 01:00:00.000000000 +0100`
`+++ /usr/sbin/ddclient	2023-12-25 20:00:49.618083219 +0100`
`@@ -4770,19 +4770,19 @@`
` `
`             } elsif ($state =~ /^results/) {`
`                 $state = 'results2';`
`-`
`+                $line =~ s|<.+?>||g;`
`                 my ($status) = $line =~ /^(\S*)\b.*/;`
`                 my $h = shift @hosts;`
` `
`                 $config{$h}{'status-ipv4'} = $status if $ipv4;`
`                 $config{$h}{'status-ipv6'} = $status if $ipv6;`
`-                if ($status eq 'NOERROR') {`
`+                if ($status =~ /NOERROR|OK/) {`
`                     $config{$h}{'ipv4'}  = $ipv4;`
`                     $config{$h}{'ipv6'}  = $ipv6;`
`                     $config{$h}{'mtime'} = $now;`
`                     success("updating %s: %s: IP address set to %s %s", $h, $status, $ipv4, $ipv6);`
` `
`-                } elsif ($status =~ /TOOSOON/) {`
`+                } elsif ($status =~ /TOOSOON|TOO_FREQ/) {`
`                     ## make sure we wait at least a little`
`                     my ($wait, $units) = (5, 'm');`
`                     my ($sec,  $scale) = ($wait, 1);`

**Comment by lemppari** [comment]
That seems to have fixed the problem for me too. Thanks!

**Comment by rblumel** [comment]
This also fixed my problem as well. hopefully it is implemented.

**Comment by rhansen** [comment]
I just opened pull request #713 to hopefully fix this.

@lemppari @Glandvador and @rblumel: Would all of you please test it and let me know how it goes?

**Comment by rblumel** [comment]
Seems to work for me.
