### ISSUE TITLE
3.9.1 -> 3.10.0 upgrade blocked by bug(s)

### ISSUE THREAD

**Issue by TedLyngmo** [ddclient/ddclient#598]
Fedora Core 38 came with ddclient 3.9.1. It has worked well, as have the many prior versions I've used. The newly released Fedora Core 39 includes 3.10.0 which fails miserably.

```bash
% ddclient -foreground -verbose
WARNING:  file /etc/ddclient.conf: file /etc/ddclient.conf should be owned only by ddclient or not be writable.
WARNING:  file /etc/ddclient.conf: file /etc/ddclient.conf should be owned only by ddclient or not be writable.
WARNING:  file /var/cache/ddclient/ddclient.cache: file /var/cache/ddclient/ddclient.cache should be owned only by ddclient or not be writable.
```
Let's just break there and check the state of those files:
```none
ls -l /etc/ddclient.conf /etc/ddclient.conf /var/cache/ddclient/ddclient.cache
-r-------- 1 ddclient ddclient 8333 16 nov 13.05 /etc/ddclient.conf
-r-------- 1 ddclient ddclient 8333 16 nov 13.05 /etc/ddclient.conf
-r-------- 1 ddclient ddclient 1178 16 nov 21.36 /var/cache/ddclient/ddclient.cache
```
Ok... So what state is expected?

Let's continue:
```bash
CONNECT:  dns.loopia.se
CONNECTED:  using SSL
SENDING:  GET /checkip/checkip.php HTTP/1.1
SENDING:  Host: dns.loopia.se
SENDING:  User-Agent: ddclient/3.10.0
SENDING:  Connection: close
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Server: nginx
RECEIVE:  Date: Thu, 16 Nov 2023 20:36:44 GMT
RECEIVE:  Content-Type: text/html; charset=UTF-8
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  Connection: close
RECEIVE:  Strict-Transport-Security: max-age=31536000; preload
RECEIVE:  X-Content-Type-Options: nosniff
RECEIVE:  X-Frame-Options: SAMEORIGIN
RECEIVE:
RECEIVE:  68
RECEIVE:  <html><head><title>Current IP Check</title></head><body>Current IP Address: 98.128.246.107</body></html>
RECEIVE:  0
RECEIVE:
SUCCESS:  smartips.se: skipped: IP address was already set to 98.128.246.107.
SUCCESS:  www.lyncon.se: skipped: IP address was already set to 98.128.246.107.
SUCCESS:  www.smartips.se: skipped: IP address was already set to 98.128.246.107.
INFO:     setting IP address to 98.128.246.107 for lyncon.se
UPDATE:   updating lyncon.se
CONNECT:  dns.loopia.se
CONNECTED:  using SSL
SENDING:  GET /XDynDNSServer/XDynDNS.php?system=dyndns&hostname=lyncon.se&myip=98.128.246.107&wildcard=ON&mx=smtp.lyncon.se&backmx=NO HTTP/1.1
SENDING:  Host: dns.loopia.se
SENDING:  Authorization: Basic bHluY29uLnNlOkRlc2tob3BlMCE=
SENDING:  User-Agent: ddclient/3.10.0
SENDING:  Connection: close
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Server: nginx
RECEIVE:  Date: Thu, 16 Nov 2023 20:36:45 GMT
RECEIVE:  Content-Type: text/html; charset=UTF-8
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  Connection: close
RECEIVE:  Strict-Transport-Security: max-age=31536000; preload
RECEIVE:  X-Content-Type-Options: nosniff
RECEIVE:  X-Frame-Options: SAMEORIGIN
RECEIVE:
RECEIVE:  5
RECEIVE:  nochg
RECEIVE:  0
RECEIVE:
FAILED:   updating lyncon.se: unexpected status (5)
Use of uninitialized value $h in hash element at /usr/sbin/ddclient line 4101.
Use of uninitialized value $_[0] in sprintf at /usr/sbin/ddclient line 2160.
WARNING:  updating : nochg: No update required; unnecessary attempts to change to the current address are considered abusive
Use of uninitialized value $h in hash element at /usr/sbin/ddclient line 4110.
Use of uninitialized value $h in hash element at /usr/sbin/ddclient line 4111.
Use of uninitialized value $h in hash element at /usr/sbin/ddclient line 4112.
Use of uninitialized value $h in hash element at /usr/sbin/ddclient line 4101.
Use of uninitialized value $_[0] in sprintf at /usr/sbin/ddclient line 2160.
FAILED:   updating : unexpected status (0)
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/sbin/ddclient line 1154.
FAILED:    was not updated because protocol <undefined> is not supported.
```
When run as a service, it will do this once every 300 seconds and mail me about the failure.

Downgrading to 3.9.1 makes everything work again.

My `/etc/ddclient.conf` with all the comments removed:
```none
% grep -vE '^#|^$' /etc/ddclient.conf
daemon=300                              # check every 300 seconds
syslog=yes                              # log update msgs to syslog
mail=ted                                # mail all msgs to root
mail-failure=ted                        # mail failed update msgs to root
pid=/run/ddclient/ddclient.pid          # record PID in file.
ssl=yes                                 # use ssl-support.  Works with
                                        # ssl-library
                                        # new IP is added as argument.
use=web
web=loopia
protocol=dyndns2
server=dns.loopia.se
script=/XDynDNSServer/XDynDNS.php
mx=smtp.lyncon.se                               # default MX
backupmx=no                                     # host is primary MX?
login=validloginaccordingtodocs
password=validpasswordaccordingtodocs
wildcard=yes                                    # add wildcard CNAME?
lyncon.se,www.lyncon.se,smartips.se,www.smartips.se
```

**Comment by olddog55** [comment]
Ditto.  Upgraded from Devuan 4.0 Chimaera (The systemd free release of Debian 11.1 Bullseye) to Devuan 5.0 Daedalus (Debian 12.1 Bookworm) and hit the same obstacles.

A few things to note:
 1. Although it appears to refuse an update, my experience is that it is updating when required.
 2. It is getting the current IP from 'checkip.dyndns.org' TWICE.  Why?
 3. I tried to set https (ssl=yes) on the update phase.  But then it tried to use https when getting the current IP from ''checkip.dyndns.org' but https is NOT supported on that server.
 4. I don't know the significance of the RECEIVE: status codes (13 and 0 in this case) but the existance of the 'RECEIVE:  nochg 24.250.1.1' would seem to indicate that an update was attempted for the dynamic IP but dyndns reported it was not necessary: 'nochg'.
     FAILED:   updating clarke39.homeip.net: unexpected status (13)
     WARNING:  updating : nochg: No update required; unnecessary attempts to change to the current address are considered abusive
     FAILED:   updating : unexpected status (0)
     FAILED:    was not updated because protocol <undefined> is not supported.
 5. Since a continual attempt to force an update at the default daemon interval would would probably get me banned, I have intentionally changed the interval to 2 hours pending a resolution.

Since it seems to be working somewhat OK, I have not reverted back to the older version.   With my fingers crossed..

===========================================================
DEBUG:    proxy    = <undefined>
DEBUG:    protocol = http
DEBUG:    server   = checkip.dyndns.org
DEBUG:    url      = 
DEBUG:    ip ver   = 
CONNECT:  checkip.dyndns.org
CONNECTED:  using HTTP
SENDING:  GET / HTTP/1.1
SENDING:  Host: checkip.dyndns.org
SENDING:  User-Agent: ddclient/3.10.0
SENDING:  Connection: close
SENDING:  
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Date: Sun, 19 Nov 2023 22:49:01 GMT
RECEIVE:  Content-Type: text/html
RECEIVE:  Content-Length: 105
RECEIVE:  Connection: close
RECEIVE:  Cache-Control: no-cache
RECEIVE:  Pragma: no-cache
RECEIVE:  
RECEIVE:  <html><head><title>Current IP Check</title></head><body>Current IP Address: 24.250.1.1</body></html>
DEBUG:    get_ip: using web, http://checkip.dyndns.org/ reports 24.250.1.1
DEBUG:    proxy    = <undefined>
DEBUG:    protocol = http
DEBUG:    server   = checkip.dyndns.org
DEBUG:    url      = 
DEBUG:    ip ver   = 4
CONNECT:  checkip.dyndns.org (IPv4)
CONNECTED:  using HTTP
SENDING:  GET / HTTP/1.1
SENDING:  Host: checkip.dyndns.org
SENDING:  User-Agent: ddclient/3.10.0
SENDING:  Connection: close
SENDING:  
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Date: Sun, 19 Nov 2023 22:49:02 GMT
RECEIVE:  Content-Type: text/html
RECEIVE:  Content-Length: 105
RECEIVE:  Connection: close
RECEIVE:  Cache-Control: no-cache
RECEIVE:  Pragma: no-cache
RECEIVE:  
RECEIVE:  <html><head><title>Current IP Check</title></head><body>Current IP Address: 24.250.1.1</body></html>
DEBUG:    get_ipv4: using (webv4, http://checkip.dyndns.org/) reports 24.250.1.1
DEBUG:    
DEBUG:    nic_dyndns2_update -------------------
INFO:     setting IP address to 24.250.1.1 for [MYHOST].homeip.net
UPDATE:   updating [MYHOST].homeip.net
DEBUG:    proxy    = <undefined>
DEBUG:    protocol = http
DEBUG:    server   = members.dyndns.org
DEBUG:    url      = nic/update?<redacted>
DEBUG:    ip ver   = 
CONNECT:  members.dyndns.org
CONNECTED:  using HTTP
SENDING:  GET /nic/update?system=dyndns&hostname=[MYHOST].homeip.net&myip=24.250.1.1 HTTP/1.1
SENDING:  Host: members.dyndns.org
SENDING:  Authorization: Basic ZGFiZHluOTozRlR0UnFQVFFobWU5WlFn
SENDING:  User-Agent: ddclient/3.10.0
SENDING:  Connection: close
SENDING:  
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Date: Sun, 19 Nov 2023 22:49:04 GMT
RECEIVE:  Server: Apache/2.4.37 (Oracle Linux) mod_apreq2-20090110/2.8.0 mod_perl/2.0.12 Perl/v5.26.3
RECEIVE:  X-UpdateCode: n
RECEIVE:  Content-Type: text/plain
RECEIVE:  Accept-Ranges: none
RECEIVE:  X-User-Status: vip
RECEIVE:  Connection: close
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  
RECEIVE:  13
RECEIVE:  nochg 24.250.1.1
RECEIVE:  0
RECEIVE:  
FAILED:   updating [MYHOST].homeip.net: unexpected status (13)
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4103.
Use of uninitialized value $_[0] in sprintf at /usr/bin/ddclient line 2160.
WARNING:  updating : nochg: No update required; unnecessary attempts to change to the current address are considered abusive
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4112.
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4113.
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4114.
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4103.
Use of uninitialized value $_[0] in sprintf at /usr/bin/ddclient line 2160.
FAILED:   updating : unexpected status (0)
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
FAILED:    was not updated because protocol <undefined> is not supported.
===========================================================
( Dynamic IP and host name are obfuscated. )

Additional debug output is available if needed.

regards,

/dave

**Comment by TedLyngmo** [comment]
I also tried the currently latest commit (9145dc1bfd78a4a901f7a8aedc00a7591736735c - v3.11.1 + 4 commits)  and that works fine.

**Comment by olddog55** [comment]
And I 'simplified' my 3.10.0 configuration by removing all the ipv4 and ipv6 specific commands, setting both usev4 and usev6 to '=no'.  And now no errors and everything seems to work perfectly using only the deprecated commands.  

My working config:   ( I have no need for IPv6 )
````## /etc/ddclient.conf
use=web
usev6=no
usev4=no
server=members.dyndns.org
login=MYLOGIN password='MYSECRET'
[MYSYSTEM1].homeip.net
[MYSYSTEM2].broke-it.net
## The_End

**Comment by LenardHess** [comment]
Hey everyone - just as a heads up, I'm first focussing on getting v3.11.2 out of the door due to an update spam/cache issue ( #595 ).
After that I'll be taking a look at why the older 3.10.0 is misbehaving - That version is from before I took over maintainership

**Comment by rocketraman** [comment]
Same problem here with 3.10.0 on Fedora 39. As with OP, downgrading to 3.9.1 fixes the issue.

I use `use=cmd, cmd='cat /some/state/file'`, which simply reads the IP address from `/some/state/file`.

I believe the problem is because 3.10.0 sends an `HTTP/1.1` request, which causes some servers to respond with `Transfer-Encoding: chunked` -- but the client interprets the chunk length as body content:

```
SENDING:  GET /nic/update?system=dyndns&hostname=Home&myip=184.145.2.112 HTTP/1.1
SENDING:  Host: updates.opendns.com
SENDING:  Authorization: Basic <elided>
SENDING:  User-Agent: ddclient/3.10.0
SENDING:  Connection: close
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  vary: Accept-Encoding
RECEIVE:  content-type: text/html; charset=UTF-8
RECEIVE:  date: Sat, 06 Jan 2024 00:09:16 GMT
RECEIVE:  server: opendns
RECEIVE:  x-envoy-upstream-service-time: 98
RECEIVE:  x-ingress-point: yyz
RECEIVE:  x-xss-protection: 1; mode=block
RECEIVE:  strict-transport-security: max-age=31536000; includeSubDomains
RECEIVE:  connection: close
RECEIVE:  transfer-encoding: chunked
RECEIVE:
RECEIVE:  12
RECEIVE:  good 184.145.2.112
RECEIVE:  0
FAILED:   updating Home: unexpected status (12)
```

Note the request HTTP/1.1, and transfer-encoding: chunked in the response, and the `unexpected status (12)` which is the length of the response chunk.

By contrast, 3.9.1 uses HTTP/1.0 and there are no problems:

```
SENDING:  GET /nic/update?system=dyndns&hostname=Home&myip=184.145.2.112 HTTP/1.0
SENDING:   Host: updates.opendns.com
SENDING:   Authorization: Basic <elided>
SENDING:   User-Agent: ddclient/3.9.1
SENDING:   Connection: close
SENDING:
SENDING:
RECEIVE:  HTTP/1.0 200 OK
RECEIVE:  vary: Accept-Encoding
RECEIVE:  content-type: text/html; charset=UTF-8
RECEIVE:  date: Sat, 06 Jan 2024 00:12:48 GMT
RECEIVE:  server: opendns
RECEIVE:  x-envoy-upstream-service-time: 96
RECEIVE:  x-ingress-point: yyz
RECEIVE:  x-xss-protection: 1; mode=block
RECEIVE:  strict-transport-security: max-age=31536000; includeSubDomains
RECEIVE:  connection: close
RECEIVE:
RECEIVE:  good 184.145.2.112
SUCCESS:  updating Home: good: IP address set to 184.145.2.112
```

**Comment by rocketraman** [comment]
Ok, upon further research I see issues https://github.com/ddclient/ddclient/issues/548 and https://github.com/ddclient/ddclient/issues/483 so the issue appears to be exactly as I described above, and should be fixed in 3.11.0_1 and above which use libcurl instead of custom request/response code.

The workaround for 3.10.0 is to include `curl=yes` in the configuration.

**Comment by LenardHess** [comment]
Hey everyone - I just pushed an initial [list of known issues](https://github.com/ddclient/ddclient/blob/05c18fce675e8b62b6c0fa9b757f2f014c733a0c/README.md#known-issues), some of which apply here.

**Comment by TedLyngmo** [comment]
Upgrading to the new `3.11.2-1.fc39` resolved the issue without having to change any configuration.
