### ISSUE TITLE
Support API Tokens in Cloudflare

### ISSUE THREAD

**Issue by DaveSophoServices** [ddclient/ddclient#73]
Requires a different header, but that's about it, I believe

https://api.cloudflare.com/#getting-started-requests

**Comment by hackerb9** [comment]
When you implement it, could you please allow us to keep using ddclient's "password=" field instead of adding a cloudflare specific API token variable? It should be possible since the X-Auth key and the API token are very different formats. (hexadecimal versus alphanumerics).

If it helps, you can check the validity of an API token using curl:

For example, the below will give an error (invalid format), but if you put your API token in it, it will return success.

```
curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify"  \
      -H "Authorization: Bearer 206aa783da3d02eca0abcde0ceb8019cdcf92" \
      -H "Content-Type:application/json"
```

**Comment by sixcorners** [comment]
I was going to post an issue about wishing that the cloudflare provider would escape email tags but if this were implemented it would obviate that.
If you didn't want to rely on the tokens being a different looking kind of password maybe you could test the login value? If the login value is omitted or set to a special value then password is a token.

**Comment by Northbadge** [comment]
#102 has implemented this
