### ISSUE TITLE
Should mkdir /var/cache/ddclient if non-existent

### ISSUE THREAD

**Issue by hackerb9** [ddclient/ddclient#76]
```
# ddclient -debug -foreground
DEBUG:    proxy  = 
DEBUG:    url    = http://checkip.dyndns.org/
DEBUG:    server = checkip.dyndns.org
DEBUG:    get_ip: using web, http://checkip.dyndns.org/ reports 197.113.84.132
DEBUG:    
DEBUG:     nic_cloudflare_update -------------------
DEBUG:    proxy  = 
DEBUG:    url    = https://www.cloudflare.com/zones?name=jenniferthames.com
DEBUG:    server = www.cloudflare.com
FATAL:    Cannot create file '/var/cache/ddclient/ddclient.cache'. (No such file or directory)
```

Creating the directory and running again fixed the problem.

**Comment by SuperSandro2000** [comment]
``make install`` should do that @rhansen ?

**Comment by rhansen** [comment]
Yup, `make install` will now create the directory.

**Comment by hackerb9** [comment]
Why rely on the Makefile for proper operation? Doesn't that make ddclient more brittle than it needs to be?

It is not a given that a person ran 'make install' on the same machine as the ddclient process. Bin directories are often shared across the network, but /var is not.  Also on some systems /var is cleaned out regularly by cron or even mounted from a RAM disk that is erased at each reboot. /var is not for permanent storage.

Also, some people might not run 'make install' at all. For example, if they use a package manager or if they used 'mv' to put the executable in the right place.

Please update ddclient to catch the error and (preferably) simply create the directory. If there is a reason the directory must be created in the Makefile, please have ddclient tell the user to run 'make install' instead of crashing.

Thank you.

**Comment by rhansen** [comment]
> Why rely on the Makefile for proper operation? Doesn't that make ddclient more brittle than it needs to be?

Adding code to ddclient to create the directory risks adding bugs. Usually the directory only needs to be created once, so why risk adding bugs to ddclient when `make install` can take care of it?

> 
> It is not a given that a person ran 'make install' on the same machine as the ddclient process. Bin directories are often shared across the network, but /var is not.

Such uses are extremely rare. And I'm guessing ddclient is one of many programs that will fail if `/usr/bin` is shared across machines but not `/var`.

> Also on some systems /var is cleaned out regularly by cron or even mounted from a RAM disk that is erased at each reboot. /var is not for permanent storage.

My interpretation of the [Linux FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s05.html) is that files may be deleted at any time, but **not** directories. It's not perfectly clear, however.

I have never heard of any systems that regularly clean out `/var`. In fact, [FHS says that `/var/tmp` is supposed to survive across reboots](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s15.html).

> 
> Also, some people might not run 'make install' at all. For example, if they use a package manager

The package should create the directory. If not, that's a bug in the package.

> or if they used 'mv' to put the executable in the right place.

In general, users that run `make` and then manually install instead of running `make install` should expect problems.

> Please update ddclient to catch the error and (preferably) simply create the directory.

See #242. Note that directory creation will fail if the system runs ddclient as an unprivileged user, which we recommend for security reasons.

**Comment by hackerb9** [comment]
> Adding code to ddclient to create the directory risks adding bugs. 

Thank you for the thorough response and explanation.
