### ISSUE TITLE
Can I update only an AAAA Record in CloudFlare?

### ISSUE THREAD

**Issue by tamaina** [ddclient/ddclient#77]
I want to make CloudFlare to resolve my dynamic IP address server to only IPv6 address, so I added an AAAA record to DNS setting of CF and ran DDclient, but it said `No DNS record ID found.`  
Then, I add an A record to DNS and ran DDclient, it successed, but updating of the A record was skipped because the server's IPv4 address was local (started with `192.168.`.)

In my case, the existence of A record is unnecessary, so I would like you to change the program so that A record does not need to exist.

## Environment
DDclient 3.9.0, lubuntu 19.04

**Comment by dkerr64** [comment]
@tamaina , please take a look at this alternate version of ddclient... https://github.com/astlinux-project/ddclient-curl 
We had to fork ddclient some time ago to improve its overall IPv6 support and change all the networking to just use curl.  I asked @abelbeck this morning to test your usecase and he states that it works.
Now that @DaveSophoServices has taken ddclient under his wing I would love to work on merging some of the changes we had to make back into the mainline... but that is probably a significant project to undertake and would require agreement to replace all the Perl-based networking with Curl.

**Comment by DaveSophoServices** [comment]
@tamaina We'll look into this, It's something that's required in the long term
@dkerr64 What's the advantage of using curl over IO::Socket? Are you using the curl module, or directly calling curl on the shell?

**Comment by abelbeck** [comment]
@DaveSophoServices : I'm with the same project as @dkerr64 , we use a minimal perl-cross installation of perl, it made much sense to call `/usr/bin/curl` directly to get a full featured HTTP/HTTPS IPv4/IPv6 client.

Example:
https://github.com/astlinux-project/ddclient-curl/blob/master/ddclient#L2099

I can't recall at the moment, but the CLI `curl` offers features not easily available with perl modules (or not possible at all).  Can perl modules restrict to only `AAAA` DNS lookups like the `-6` curl option does ?  That feature is required.

Our project has been using our fork `ddclient-curl` since January 2017 and has worked well for us.

BTW, we currently don't validate HTTPS certificates for compatibility during the pre-Let's-Encrypt era, but could easily drop the `--insecure` option.

@dkerr64 did a lot of development and testing to get IPv6 support working well.

**Comment by dkerr64** [comment]
Thank you @abelbeck for your comments.  As you point out this started when I set out to implement support for IPv6.  It was three years ago now so memory fades, but I ran into a number of problems with trying to use Perl IO functions both with IPv6 and with SSL.  Ultimately it just made sense to offload all the network functions into Curl, which as you point out is both robust and flexible.  That greatly simplified things within ddclient.

**Comment by abelbeck** [comment]
@dkerr64 : I also recall we chose not to implement the `ddclient` connection proxy options, though `curl` should be able to do that if desired.

We also did a major style cleanup using `perltidy`
```
perl perltidy -ce -l=132 -pt=2 -sbt=2 -bt=2 -bbt=2 -isbc ddclient
```

**Comment by rhansen** [comment]
@tamaina Did you get it working? IPv6-only for CloudFlare has been supported since v3.9.0. If it is not working, please paste your configuration so we can help you further.
