### ISSUE TITLE
use iproute2 by default, with net-tools as fallback

### ISSUE THREAD

**Issue by xogium** [ddclient/ddclient#93]
Hi,
as the title suggest, I think it would be a good time now to switch away from net-tools. this has been deprecated for years in favor of iproute2, and is only still working nowadays because the kernel did not break it... Yet.

I understand you can't change it, as in permanently get rid of this, but perhaps ddclient could start using either net-tools or iproute2 where possible, and not exclusively rely on net-tools.

**Comment by wimpunk** [comment]
Feel free to provide a patch.

**Comment by xogium** [comment]
I would do so gladly, but I am no coder. However I would be happy to try out patches people might come up with to do this, for sure

**Comment by wimpunk** [comment]
@rhansen What do you think about this?  Is debian swithing away from net-tools by default?

**Comment by rhansen** [comment]
I think all of the Linux distros are slowly switching from net-tools to iproute2. I suspect it will be a long time before net-tools is finally removed so I think this is low priority. I'd be happy to work on this, except I won't have the time any time soon.

Last time I looked at NetBSD (~5 years ago) it didn't have an equivalent to iproute2. I don't know about the other BSDs or mac OS.

**Comment by rhansen** [comment]
I added this to the ddclient 4.0 project, but I think there's a good chance it will slip to a later release.

**Comment by rhansen** [comment]
Huh, it looks like there might already be support for iproute2; see [line 2201](https://github.com/ddclient/ddclient/blob/1d78f5fbe333116888de48330163db1962ec9c94/ddclient#L2201).  Would you mind testing it @xogium? Perhaps the easiest way is to swap the order:

```perl
    } elsif ($use eq 'if') {
        $skip  = opt('if-skip', $h) || '';
        $reply = `ip addr list dev $arg 2> /dev/null`;
        $reply = `ifconfig $arg 2> /dev/null` if $?;
        $reply = '' if $?;
```

**Comment by dkerr64** [comment]
This is one of the things we cleaned up over on astlinux-project where we replaced all ifconfig with ip.  But we can do that because we control the whole platform so we know we have iproute2 package available.  I think the more general case you have to be able to work with both and I would personally prefer ip over ifconfig (so try ip first and only use if config if it is not available). 

In this particular example, when it comes to IPv6 support, the get_ip() function will use
```$reply = `ip -4 -o addr show dev $arg scope global 2>/dev/null`;```
and a new get_ipv6() function is added and will use..
```$reply = `ip -6 -o addr show dev $arg scope global 2>/dev/null`;```
which helps limit the results on whether you are looking for an IPv4 or IPv6 address.  For this to work on platforms that don't have iproute2 I need to figure out the equivalent ifconfig.

**Comment by rhansen** [comment]
Thanks for the input @dkerr64. If someone can confirm that the current iproute2 fallback works then I think we can repurpose this issue to be about changing the logic to attempt iproute2 first (and refine the command-line args while we're at it) and fall back to net-tools if iproute2 fails.

@xogium: Instead of swapping the order as I suggested in [my previous comment](https://github.com/ddclient/ddclient/issues/93#issuecomment-641538754), it would probably be better to test it by deleting `ifconfig`:

```perl
    } elsif ($use eq 'if') {
        $skip  = opt('if-skip', $h) || '';
        $reply = `ip addr list dev $arg 2> /dev/null`;
        $reply = '' if $?;
```

If you just swap the order and the `ip addr list dev $arg` command fails then it will fall back to `ifconfig` and you won't be able to tell if the `ip` command worked.

**Comment by dkerr64** [comment]
I have tested the following on Ubuntu 18.04, 20.04 and MacOS 10.15.5... If testing yourself set $arg to a valid interface.

```
#!/usr/bin/perl -w

$arg = "ens192";
$reply = `ip -4 -o addr show dev $arg scope global 2>/dev/null`;
$reply = `ifconfig $arg 2> /dev/null | grep -w "inet"` if $?;
$reply = '' if $?;
if ($reply =~ /^.*?\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b.*/is) {
  $reply = $1;
}
printf("%s", $reply);
printf("\n\r");

$reply = `ip -6 -o addr show dev $arg scope global 2>/dev/null | grep -v "deprecated"`;
$reply = `ifconfig $arg 2>/dev/null | grep -w "inet6" | grep -v "deprecated"` if $?;
$reply = '' if $?;
# Now filter for Global Unicast Address (GUA) as it would not be valid
# to try and update DNS with a link local (LLA) or Unique Local (ULA) Address
if ($reply =~ /^.*? ([23][a-f0-9]{3}:[a-f0-9:]+:[a-f0-9]{1,4})[\/| ].*/is) {
  $reply = $1;
} else {
  $reply = '';
}
printf("%s", $reply);
printf("\n\r");

exit 0;
```
You would only want to take the IPv4 version for now, but I include both here as I needed to make sure it works for IPv6 as well.

IPv6 code may require further refinement as there are multiple IPv6 addressees assigned to an interface... always a Link Local Address (LLA), usually one or more Global Unicast (GUA) and maybe a Unique Local (ULA) address.  You would never want to update DNS with a LLA or ULA (though I suppose if you were running a dynamic DNS server inside your own campus you might want to?  But that is probably out of scope).  But there can be multiple GUA... assigned by either DHCPv6, auto configuration or static.  There is no obvious way to find out from iproute2 which is which so this code just returns the first one listed by ip or ifconfig.

Enjoy!

**Comment by dkerr64** [comment]
Oh... you would want to leave out all the regex filters when you implement the code, as it is processed later in the function (after the if-skip is processed).  I have it right after the calls to ip/ifconfig for test purposes.

**Comment by rhansen** [comment]
`use=if` with IPv6 is not really expected to work, so testing with IPv4 is sufficient. Thank you!

**Comment by dkerr64** [comment]
`ifconfig` is also used within the `test_possible_ip` function.  To try `ip` first and then fallback on `ifconfig` we could use the following code...

```
my $link = `ip -o link show 2>/dev/null`;
$link = `ifconfig -a 2>/dev/null | grep "^[a-zA-Z]"` if $?;
my @links = split('\n', $link);
foreach my $if (@links) {
    $if =~ /[0-9]*(: )?(.*?)(:|\s|@)/; # extract the interface name
    $if = $2;
    printf("%s", $if);
    printf("\n\r");
}
exit 0;
```
Tested on Ubuntu 20.04, MacOS 10.15.5 and RHEL v8.2

David.
